# Generated by Django 2.0.7 on 2019-07-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='area_of_expertise',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='experince',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='keywords',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='qualification',
            field=models.CharField(default='', max_length=255),
        ),
    ]
