# Generated by Django 2.0.7 on 2019-07-10 12:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190710_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
