# Generated by Django 2.0.7 on 2019-07-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190710_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractmodel',
            old_name='name',
            new_name='cname',
        ),
    ]
