# Generated by Django 2.0.7 on 2019-07-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190711_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractmodel',
            name='cname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
