# Generated by Django 2.0.7 on 2019-07-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190711_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
