# Generated by Django 2.0.7 on 2019-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190711_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractmodel',
            name='requirements',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
