# Generated by Django 2.0.7 on 2019-07-11 06:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20190711_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
