# Generated by Django 2.0.7 on 2019-07-11 06:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20190711_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractmodel',
            name='cname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extractmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='extractmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='extractmodel',
            name='requirements',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
