# Generated by Django 2.0.7 on 2019-07-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_extractmodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractModel2',
        ),
    ]
